# Generated by Django 6.0.2 on 2026-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
