# Generated by Django 6.0.2 on 2026-02-19 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tab_low_stock_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('daily_limit_per_user', models.IntegerField(default=1)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='tab',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='user',
        ),
        migrations.CreateModel(
            name='TabletDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('return_pending', 'Return Pending'), ('repair', 'Repair')], default='available', max_length=20)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tab_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='core.tabtype')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tabletdevice')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tabletdevice')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.DeleteModel(
            name='Tab',
        ),
        migrations.DeleteModel(
            name='UsageLog',
        ),
    ]
