# Generated by Django 6.0.2 on 2026-02-19 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tabtype_remove_usagelog_tab_remove_usagelog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('tab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tabtype')),
            ],
        ),
    ]
