# Generated by Django 6.0.2 on 2026-03-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignmentotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlog',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
